config/routes.rb
Rails.application.routes.draw do
  post  'sheet_manage/create_all'
  patch 'sheet_manage/create_all'
  get   'sheet_manage/create_all'
  post  'sheet_manage/haihu'
  post  'sheet_manage/del'
#   get 'po_sheets/create'
#   get   'ajtest', to: 'po_sheets#ajtest'

  get   'po_sheets/show/:id/:editmode', to: 'po_sheets#show'
#  post  'po_sheets/show/:id/:editmode', to: 'po_sheets#show'
  patch 'po_sheets/show/:id/:editmode', to: 'po_sheets#save'
  get   'po_sheets/show/:id', to: 'po_sheets#show'
  post  'po_sheets/show/:id', to: 'po_sheets#show'
  patch 'po_sheets/show/:id', to: 'po_sheets#save'

  get  'po_sheets/save'
  post 'po_sheets/save'

  get 'po_sheets/index'
  get 'po_sheets', to: 'po_sheets#index'

  get 'po_sheets/sheets_all'

  resources :staffs
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'login/chg_nenki'
  get  'login/index_hr'

  get  'login/index'
  post 'login/index'
  get 'login/stafflist'
  get 'login', to: 'login#index'
  root :to => 'login#index'
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :account
  has_many :sheet_author, :class_name => 'PoSheet', :foreign_key => 'author_id'
  has_many :sheet_1stev, :class_name => 'PoSheet', :foreign_key => 'primary_evaluator_id'
  has_many :sheet_2ndev, :class_name => 'PoSheet', :foreign_key => 'secondary_evaluator_id'
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(
        :staff_no, :name,
        :department,
        :dep_1st,
        :dep_2nd,
        :dep_3rd,
        :dep_bunshitsu,
        :position,
        :email,
        :tokyu,
        :grade,
        )
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff, local: true) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :staff_no %>
    <%= form.text_field :staff_no %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label "等級" %>
    <%= form.text_field :tokyu %>
  </div>

  <div class="field">
    <%= form.label "grade" %>
    <%= form.text_field :grade %>
  </div>

  <div class="field">
    <%= form.label :dep_1st %>
    <%= form.text_field :dep_1st %>
  </div>

  <div class="field">
    <%= form.label :dep_2nd %>
    <%= form.text_field :dep_2nd %>
  </div>

  <div class="field">
    <%= form.label :dep_3rd %>
    <%= form.text_field :dep_3rd %>
  </div>

  <div class="field">
    <%= form.label :dep_bunshitsu %>
    <%= form.text_field :dep_bunshitsu %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Staff no</th>
      <th>Name</th>
      <th>Dep 1st</th>
      <th>Dep 2nd</th>
      <th>Dep 3rd</th>
      <th>Dep bunshitsu</th>
      <th>Position</th>

      <th>等級</th>
      <th>grade</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td style="padding:0px 5px"><%= staff.staff_no %></td>
        <td style="padding:0px 5px"><%= staff.name %></td>
        <td style="padding:0px 5px"><%= staff.dep_1st %></td>
        <td style="padding:0px 5px"><%= staff.dep_2nd %></td>
        <td style="padding:0px 5px"><%= staff.dep_3rd %></td>
        <td style="padding:0px 5px"><%= staff.dep_bunshitsu %></td>
        <td style="padding:0px 5px"><%= staff.position %></td>
        <td style="padding:0px 5px"><%= staff.tokyu %></td>
        <td style="padding:0px 5px"><%= staff.grade %></td>
        <td style="padding:0px 5px"><%= link_to 'Show', staff %></td>
        <td style="padding:0px 5px"><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td style="padding:0px 5px"><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Staff no:</strong>
  <%= @staff.staff_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @staff.department %>
</p>

<p>
  <strong>Dep 1st:</strong>
  <%= @staff.dep_1st %>
</p>

<p>
  <strong>Dep 2nd:</strong>
  <%= @staff.dep_2nd %>
</p>

<p>
  <strong>Dep 3rd:</strong>
  <%= @staff.dep_3rd %>
</p>

<p>
  <strong>Dep bunshitsu:</strong>
  <%= @staff.dep_bunshitsu %>
</p>

<p>
  <strong>Position:</strong>
  <%= @staff.position %>
</p>

<p>
  <strong>Email:</strong>
  <%= @staff.email %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>