config/routes.rb
Rails.application.routes.draw do
  post  'sheet_manage/create_all'
  patch 'sheet_manage/create_all'
  get   'sheet_manage/create_all'
  post  'sheet_manage/haihu'
  post  'sheet_manage/del'
#   get 'po_sheets/create'
#   get   'ajtest', to: 'po_sheets#ajtest'

  get   'po_sheets/show/:id/:editmode', to: 'po_sheets#show'
#  post  'po_sheets/show/:id/:editmode', to: 'po_sheets#show'
  patch 'po_sheets/show/:id/:editmode', to: 'po_sheets#save'
  get   'po_sheets/show/:id', to: 'po_sheets#show'
  post  'po_sheets/show/:id', to: 'po_sheets#show'
  patch 'po_sheets/show/:id', to: 'po_sheets#save'

  get  'po_sheets/save'
  post 'po_sheets/save'

  get 'po_sheets/index'
  get 'po_sheets', to: 'po_sheets#index'

  get 'po_sheets/sheets_all'

  resources :staffs
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'login/chg_nenki'
  get  'login/index_hr'

  get  'login/index'
  post 'login/index'
  get 'login/stafflist'
  get 'login', to: 'login#index'
  root :to => 'login#index'
end

app/models/po_sheet.rb
class PoSheet < ApplicationRecord
    has_many :objectives
    belongs_to :author, :class_name => 'Staff'
    belongs_to :primary_evaluator, :class_name => 'Staff'
    belongs_to :secondary_evaluator, :class_name => 'Staff'

    accepts_nested_attributes_for :objectives
 

end

app/controllers/po_sheets_controller.rb
class PoSheetsController < ApplicationController
  #before_action :authenticate_account!
  layout 'aj'

  def index
    @data = PoSheet.all
    @dataobj = Objective.all
  end

  def show
    @sheet = PoSheet.find(params[:id])
    params[:editmode] == :edit.to_s ?  @mode = :edit : @mode = :show
  end

  def del
    objst = PoSheet.all
    objst.each { |i| i.destroy }

    objs = Objective.all
    objs.each { |i| i.destroy }

    redirect_to '/po_sheets/index'
  end

  def sheets_all
  end

  def edit

    @sheet = PoSheet.find(params[:id])
    @mode = "edit"
    redirect_to '/po_sheets/show/' + params[:id] + '/edit'
  end

  def save
    if request.patch? then
      @sheet = PoSheet.find(params[:id])
      @sheet.update!(sheet_params)
    end
    redirect_to '/po_sheets/show/' + params[:id]
  end

  private
  def sheet_params
    params.require(:po_sheet).permit(
      :status,
      :season_index,
      :sheet_type,
      :year,
      :period,
      :tokyu,
      :grade,
      :grade_c,
      :grade_reason,
      :position,
      :department,
      :department_c,
      :notices,
      :sales_plan,
      :profit_plan,
      :sales_result,
      :profit_result,
      :total_point,
      :zone_primary,
      :zone_secondary,
      :author_id,
      :primary_evaluator_id,
      :secondary_evaluator_id,
      :objective_id,
      objectives_attributes: [
        :id,
        :titel,
        :content,
        :difficulty,
        :weight,
        :consequence,
        :consequence_evaluator,
        :self_evaluation,
        :primary_evaluation,
        :secondary_evaluation,
        :point,
        :po_sheet_id,
      ]
    )

  end
end

app/helpers/po_sheets_helper.rb
module PoSheetsHelper
end

app/views/po_sheets/_authorinfo.html.erb
<br>
<table style = "table-layout: fixed;">

    <tbody>
        <tr>
            <th class="hd" style="width: 50px;">期</th>
            <td class="center">
              <%= @sheet.year %> </td>

            <th class="hd" style="width: 40px;" >上・下</th>
            <td class="center"><%= @sheet.period %></td>
            <td colspan="2">   </td>
        </tr>
        <tr>
            <th class="hd">等級</th>
            <td class="center"><%=@sheet.tokyu %></td>

            <th class="hd">ｸﾞﾚｰﾄﾞ</th>
            <td class="center"><%=@sheet.grade %></td>

            <th class="hd" style="width:30px;">役職</th>
            <td style="width:200px;"><%= @sheet.position %></td>
        </tr>
        <tr>
            <th class="hd">目標時点<br>の所属</th>
            <td colspan="5"><%= @sheet.department %></td>
        </tr>
        <tr>
            <th class="hd">社員番号</th>
            <td colspan="2"><%= @sheet.author.staff_no %> </td>

            <th style="width:30px;">氏名</th>
            <td colspan="2"><%= @sheet.author.name %> </td>
        </tr>
    </tbody>
</table>

app/views/po_sheets/_changeinfo.html.erb
<table style="margin-left: 30px;">
	<tbody>
		<tr>
			<th>変更後<br>ｸﾞﾚｰﾄﾞ</th>
			<td style="width: 50px;">
				<% if @fix == true %>
					<%= @sheet.grade_c %>
				<% else %>
					<%= form.select(:grade_c,
						1..10,
						{:include_blank => true},
						{:value => @sheet.grade_c,
						:disabled => @fix }
					) %>
				<% end %>

			<td style="width: 250px;"></td>
		</tr>
		<tr>
			<th>ｸﾞﾚｰﾄﾞの<br>変更理由</th>
			<td colspan="2">
				<%= form.text_field(:grade_reason,
				  :value => @sheet.grade_reason,
					:disabled => @fix ) %>
			</td>

		</tr>
		<tr>
			<th>評価時点<br>の所属</th>
			<td colspan="2"><%= form.text_field(:department, :value => @sheet.department, :disabled => @fix) %></td>

		</tr>
	</tbody>
</table>

app/views/po_sheets/_evaluatorinfo.html.erb
<br>
<table align="right" style = "width: 90%">
	<tbody>
		<tr>
			<th rowspan="3" style="width:40px;">一次<br>評価者</th>
			<td rowspan="3" style="width:40px;">
				<%= form.text_field(
					:zone_primary,
					:value => @sheet.zone_primary,
					:disabled => @fix,
					:style => "text-align:center;" ,
					:id => ("zone_primary")) %>
			</td>
			<th colspan="2">一次評価者</th>
		</tr>
		<tr>
			<th style = "width:50px;">社員番号</th>
			<td style = "width:150px;">
			<%= @sheet.primary_evaluator.staff_no %></td>
		</tr>
		<tr>
			<th>氏名</th>
			<td><%=@sheet.primary_evaluator.name %></td>
		</tr>
		<tr>
			<th rowspan="3">二次<br>評価者</th>
			<td rowspan="3">
				<%= form.text_field(
					:zone_secondary,
					:value => @sheet.zone_secondary,
					:disabled => @fix,
					:style => "text-align:center;" ,
					:id => ("zone_secondary")) %>
			</td>
			<th colspan="2">二次評価者(修正がある場合のみ)</th>
		</tr>
		<tr>
			<th>社員番号</th>
			<td><%=@sheet.secondary_evaluator.staff_no%></td>
		</tr>
		<tr>
			<th>氏名</th>
			<td><%=@sheet.secondary_evaluator.name %></td>
		</tr>
	</tbody>
</table>

app/views/po_sheets/_objectives_info.html.erb
<% ct = 0 %>
<% obtype = ["顧<br>客","育<br>成","組<br>織"] %>
<% arr_difficulty = ["","H","M","L"] %>
<% arr_evaluation = ["","◎","〇","△","▲"] %>
<% arr_weight = ["","5%","10%","15%","20%","25%","30%"] %>

<% arr_title = [
    ["リストから選択",
     "徹底的に差別化を追及せよ",
     "お客様の期待を凌駕するサービスを提供せよ"],
    ["リストから選択",
     "自らのスキル向上に自らが取り組め、組織は業務を通じて人を育てよ",
     "上司・年配者は率先垂範し、自らの背中で語れ"],
] %>

<br>
<table>
    <tbody>
        <tr style = "border-top-style: hidden; border-left-style: hidden;">
            <td style="border-right-style: hidden; width: 20px;"></td>
            <td style="border-right-style: hidden; width: 20px;"></td>
            <td style="border-right-style: hidden; width: 20px;"></td>
            <td style="border-right-style: hidden; width:300px;"></td>
            <td style="border-right-style: hidden; width: 40px;"></td>
            <td style="border-right-style: hidden; width: 40px;"></td>
            <td style="border-right-style: hidden; width: 40px;"></td>
            <td style="border-right-style: hidden; width:200px;"></td>
            <td style="border-right-style: hidden; width: 40px;"></td>
            <td style="border-right-style: hidden; width: 40px;"></td>
            <td style="border-right-style: hidden; width: 40px;"></td>
            <td style="border-right-style: hidden; width:200px;"></td>
        </tr>
        <tr>
            <th colspan="7">期首に設定する内容</th>
            <th colspan="2">期首の結果内容（期末）</th>
            <td colspan="3"></td>
        </tr>
        <tr>
            <th colspan="4">今期求めるもの</th>
            <th>難易度</th>
            <th colspan="2">ウェイト</th>
            <th>遂行結果</th>
            <th>自己評価</th>
            <th>上長評価</th>
            <th>ポイント</th>
            <th>遂行結果確認・補足事項記入欄 <br> 評価者記入</th>
        </tr>

      <%= form.fields_for :objectives do |ob| %>
      <%= ob.hidden_field(:id) %>

        <tr>
          <% if ct == 0  then %>
            <th rowspan="6">ハ<br>ッ<br>ピ<br>｜<br>ト<br>ル<br>ネ<br>｜<br>ド</th>
          <% end %>
          <% if ct <= 2  then %>
            <th rowspan="2"><%= obtype[ct].html_safe %></th>
            <th rowspan="2"> </th>
          <% elsif ct == 3 then %>
            <th rowspan="10" colspan="3"> 通常業務</th>
          <% end %>

        <%# タイトル %>
            <td colspan="3" style="height: 10px;" class = "ob">
              <% if ct <= 1 then %>
                <% if @fix == true %>
                  <%= @sheet.objectives[ct].titel %>
                <% else %>
                  <%= ob.select(:titel, arr_title[ct],
                    {},
                    {:class => "fit"}
                  ) %>
                <% end %>

              <% elsif %>
                <%= ob.text_field(
                    :titel,
                    :value => @sheet.objectives[ct].titel,
                    :disabled => @fix,
                    ) %>
              <% end %>
            </td>

            <td rowspan="2"></td> <%# ウェイトの説明 %>

        <%# 遂行結果 %>
            <td class="txt" rowspan="2">
              <%= ob.text_area(
                :consequence,
                :value => @sheet.objectives[ct].consequence,
                :disabled => @fix ) %>
            </td>

        <%# 自己評価 %>
            <td rowspan="2" style = "text-align:center;" >
              <% if @fix == true %>
                <%= @sheet.objectives[ct].self_evaluation %>
              <% else %>
                <%= ob.select( :self_evaluation, arr_evaluation,
                    :value => @sheet.objectives[ct].self_evaluation ) %>
              <% end %>
            </td>

        <%# 上長評価 %>
            <td rowspan="2" style = "text-align:center;" >
              <% if @fix == true %>
                <%= @sheet.objectives[ct].primary_evaluation %>
              <% else %>
                <%= ob.select( :primary_evaluation, arr_evaluation,
                  {:value => @sheet.objectives[ct].primary_evaluation},
                  {:class => ("e" + ct.to_s),}
                ) %>
              <% end %>
            </td>

        <%# ポイント %>
            <td rowspan="2" class="point">
              <%= ob.text_field(
                    :point,
                    :value => @sheet.objectives[ct].point,
                    :disabled => @fix,
                    :style => "text-align:center;" ,
                    :class => "point_field",
                    :id => ("p" + ct.to_s) ) %>
            </td>

        <%# 遂行結果 評価者記入 %>
            <td class="txt" rowspan="2">
              <%= ob.text_area(
                :consequence_evaluator,
                :value => @sheet.objectives[ct].consequence_evaluator,
                :disabled => @fix ) %>
            </td>
        </tr>
        <tr>
        <%# 内容 %>
            <td class="txt" class = "ob">
              <%= ob.text_area(
                :content,
                :value => @sheet.objectives[ct].content,
                :disabled => @fix ) %>
            </td>

        <%# 難易度 %>
            <td style = "text-align:center;" >

              <% if @fix == true %>
                <%= @sheet.objectives[ct].difficulty %>
              <% else %>
                <%= ob.select(
                  :difficulty,
                  arr_difficulty,
                  {:value => @sheet.objectives[ct].difficulty,},
                  {:class => ("d" + ct.to_s)}
                  ) %>
              <% end %>
            </td>

        <%# ウェイト %>
            <td style = "text-align:center;" >
              <% if @fix == true %>
                <%= @sheet.objectives[ct].weight %>
              <% else %>
                <%= ob.select(
                      :weight,
                      ["",5,10,15,20,25,30],
                      {},
                      { :value => @sheet.objectives[ct].weight,
                        :disabled => @fix,
                        :class => "weight",
                      :id => ("w" + ct.to_s)}) %>
              <% end %>
            </td>

        </tr>
        <%# 繰り返し完了 %>
      <% if ct == 7 %>
        <tr>
            <td colspan="3"></td>
            <td></td>
            <th>合計</th>
            <td><%# ウェイト合計 %>
              <%= form.text_field(
                :total_point,
                :value => @sheet.total_point,
                :disabled => @fix,
                :style => "text-align:center;" ,
                :id  => "weight_total") %>
            </td>
            <td></td>
            <td></td>
            <td></td>
            <th style="height:40px">合計</th>

        <%# ポイント合計 %>
            <td>
              <%= form.text_field(
                :total_point,
                :value => @sheet.total_point,
                :disabled => @fix,
                :style => "text-align:center;" ,
                :id => ("point_total") ) %>
            </td>
            <td></td>
        </tr>
      <% end %>

      <% ct += 1 %>
      <% end %>  <%# 繰り返し完了 %>
    </tbody>


</table>

app/views/po_sheets/_objinfo.html.erb
<table>
    <tbody>
            <tr>
                <td style="width: 20px;"></td>
                <td style="width: 20px;"></td>
                <td style="width: 20px;"></td>
                <td style="width:300px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td style="width:200px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>    
            <tr>
                <th colspan="7">期首に設定する内容</th>
                <th colspan="2">期首の結果内容（期末）</th>
                <td colspan="3"></td>
            </tr>
            <tr>
                <th colspan="4">今期求めるもの</th>
                <th>難易度</th>
                <th colspan="2">ウェイト</th>
                <th>遂行結果</th>
                <th>自己評価</th>
                <th>上長評価</th>
                <th>ポイント</th>
                <th>遂行結果確認・補足事項記入欄 <br> 評価者記入</th>
            </tr>

            <%= 3.times do |k| %>
                <tr>
                    <th> </th>
                    <th rowspan="2">顧<br>客</th>
                    <th rowspan="2">必<br>須<br>入<br>力</th>
                    <td colspan="3"> </td>
                    
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td class="txt"></td>
                    <td><%= ob.text_field(:content, :value => @sheet.objectives[k].content, :disabled => @fix) %></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                
            <% end %> 
            
            <tr>
                <th colspan="3" rowspan="5">通常業務</th>
                <td class="txt"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td colspan="3"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
    </tbody>
    
</table>

app/views/po_sheets/_plan_resultinfo.html.erb
<br>
<table>
    <tbody>
    <tr>
        <th rowspan="4" style="width: 20px;">計<br>数<br>計<br>画</th>
        <th></th>
        <th></th>
        <th style="width: 40px;">計画</th>
        <th style="width: 40px;">実績</th>
        <th>差異</th>
        <th>達成率</th>
        <th>係数</th>
        <th>係数計画<br>ウェイト</th>
    </tr>
    <tr>
        <th>入力不要</th>
        <th>受注</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td rowspan="3" style="text-align:center;">50%</td>
    </tr>
    <tr id="sales">
        <th>必須入力</th>
        <th>売上</th>
      <%#売り上げ計画 %>
        <td>
            <%= form.text_field(
                :sales_plan,
                :value => @sheet.sales_plan,
                :disabled => @fix,
                :id => "sel_p",
            ) %>
        </td>

      <%#売り上げ実績 %>
        <td>
            <%= form.text_field(
                :sales_result,
                :value => @sheet.sales_result,
                :disabled => @fix,
                :id => "sel_r",
            ) %>
        </td>
      <%#売り上げ差異 %>
        <td><div id = "sel_sai"></div></td>

      <%#売り上げ達成率 %>
        <td><div id="sel_rate"></div></td>

      <%#売り上げ計数 %>
        <td><div id="sel_pt"></div></td>
    </tr>
    <tr id="profit">
        <th>必須入力</th>
        <th>利益</th>
        <td>
            <%= form.text_field(
                :profit_plan,
                :value => @sheet.profit_plan,
                :disabled => @fix,
                :id => "pro_p",
            ) %>
        </td>
        <td>
            <%= form.text_field(
                :sales_result,
                :value => @sheet.sales_result,
                :disabled => @fix,
                :id => "pro_r",
            ) %>
        </td>
        <td><div id="pro_sai"></div></td>
        <td><div id="pro_rate"></div></td>
        <td><div id="pro_pt"></div></td>
    </tr>
    </tbody>
</table>
<br>

app/views/po_sheets/create.html.erb
<h1>PoSheets#create</h1>
<p>Find me in app/views/po_sheets/create.html.erb</p>

<talbe>
  <%= form_for @po_sheets, url:{controller:'', action:''} do |form| %>
  <tr>
    <td>
    </td>
  <td/>

  <% end %>
</talbe>

app/views/po_sheets/index.html.erb
<h1>PoSheets#index</h1>


<br>

<table>
<% @data.each do |obj| %>
<tr>
  <td><%= obj.id %>---</td>
  <td><%= obj.year %>---</td>
  <td><%= obj.period %>---</td>
  <td><%= obj.notices %>---</td>

  <% obj.objectives.each do |j| %>
  <td><%=  j.id %></td>
  <% end %>

</tr>
<% end %>

</table>

<br>

<table>
<% @dataobj.each do |obj| %>
<tr>
  <td><%= obj.id %> </td>
  <td>--<%= obj.content %> --</td>
</tr>

<% end %>
</table>


<p>
<a href="/po_sheets/create">create</a>
</p>
<a href="/po_sheets/del">delete</a>

app/views/po_sheets/sheets_all.html.erb
<h1>PoSheets#sheets_all</h1>
<p>Find me in app/views/po_sheets/sheets_all.html.erb</p>

app/views/po_sheets/show.html.erb
<div>
<%= link_to '[Top]', "/login/index"%> &nbsp;&nbsp;
<%= link_to 'ログアウト', destroy_account_session_path, method: :delete %>&nbsp;&nbsp;
<%#= current_account.id == @sheet.author_id ? "あなたのシート" : ""%>
</div>

<% @mode == :edit ? @fix = false : @fix = true %>
<h1>個人目標 兼 業績シート
<%= @sheet.sheet_type%>用
【<%=@sheet.status%>】
<%= @fix ?  "" : "＜編集中＞" %> </h1>

<%status_arr = [
  "目標作成中",
  "目標上長確認中",
  "目標人事確認中",
  "実施中",
  "結果入力中",
  "結果上長確認中",
  "すり合わせ",
  "結果人事確認中",
  "完了",
  "廃止",]%>

<%unless @fix  %>
  <%= form_for(@sheet, url:{cotroller: "po_sheets", action: "save"}) do |sts|%>
    ステータス変更  :
    <%= sts.select(:status, options_for_select(status_arr, :selected => @sheet.status))%>
    <%= sts.submit("変更") %>
  <% end %>
<%end%>

<%= form_for(@sheet, url:{cotroller: "po_sheets", action: "save"}) do |form| %>

<%if @fix  %>
  <a href="/po_sheets/show/<%= params[:id] + "/edit" %>"> [編集]</a>
<%else%>
  <a href="/po_sheets/show/<%= params[:id] %>">[戻る]</a>&nbsp;&nbsp; <%= form.submit("保 存",) %>
<%end%>

<br>

<table style = "table-layout: fixed; width: 1200px;" class="pos">
  <tbody>
    <tr class="pos">
      <td class="pos" style="width: 400px;">
        <%= render partial: 'authorinfo', locals:{:form => form} %></td>
      <td class="pos" style="width: 400px;">
        <%= render partial: 'changeinfo', locals:{:form => form} %></td>
      <td class="pos">
        <%if @sheet.sheet_type =="定量" %>
        <%= render partial: 'plan_resultinfo' , locals:{:form => form} %>
        <%end %>
      </td>
    </tr>

    <tr>
      <td class="pos" colspan="3">
        <%= render partial: 'objectives_info' , locals:{:form => form} %>
      </td>
    </tr>


    <tr class="pos">
      <td class="pos" colspan = "2">

        <div style = "display:table-row">
          <div style = "display:table-cell; vertical-align:">
            <table style="display">
              <tbody>
                <tr><th style="text-align: left;">
                  【特記事項】業務を遂行する中で、その結果に
                    <br>大きく影響を及ぼした環境要因があれば記入
                </th></tr>
                <tr><td>
                  <%= form.text_area(
                    :notices,
                    :value => @sheet.notices,
                    :disabled => @fix ) %>
                </td></tr>
              </tbody>
            </table>

          </div>
          <div style = "display:table-cell; vertical-align: top; padding-left: 20px;">
            <table>
              <tbody>
                <tr>
                  <th style="width:50px">難易度</th><th style="width:40px">乗率</th><th>基準</th>
                  <th colspan="2">評価およびポイント</th>
                </tr>
                <tr>
                  <td class="center">H</td><td class="center">1.2</td>
                  <td>現グレードの水準を超える目標 </td>
                  <td>◎：大幅に目標を達成している</td>
                  <td class="center">120</td>
                </tr>
                <tr>
                  <td class="center">M</td><td class="center">1.0</td>
                  <td>グレードに見合った目標</td>
                  <td>〇：目標を達成している</td>
                  <td class="center">100</td>
                </tr>
                <tr>
                  <td class="center">Ⅼ</td><td class="center">0.8</td>
                  <td>現グレードの水準を下回る目標</td>
                  <td>△：目標に達成していない</td>
                  <td class="center">50</td>
                </tr>
                <tr>
                  <td colspan="3">※大幅達成の目安は120％以上の成果</td>
                  <td>▲：大幅に目標を達成していない</td>
                  <td class="center">0</td>
                </tr>
              </tbody>
            </table>
          </div>

        </div>

      <td class="pos">
        <%= render partial: 'evaluatorinfo', locals:{:form => form} %>
      </td>
    </tr>

  </tbody>
</table>

<% end %>
<br>